apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: test-description-rule
spec:
  groups:
  - name: Description
    rules:
    - alert: DescriptionAlert
      annotations:
        summary: TestSummary
        description: TestDescription
        runbook_url: TestRunbookURL
      labels:
        severity: TestSeverity
