apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: test-message-rule
spec:
  groups:
  - name: Message
    rules:
    - alert: MessageAlert
      annotations:
        summary: TestSummary
        message: TestMessage
        runbook_url: TestRunbookURL
      labels:
        severity: TestSeverity
